### ISSUE TITLE
Special buttons to label the type of comment 

### ISSUE THREAD

**Issue by hugoduar** [Proyecto-Nutria/feedback-helper#9]
I've noticed that some comments are preceded by a character which means the type of feedback you are giving (+, ?, and so on), is it possible to have a special button to add them using the tool? 

Thanks!

**Comment by searleser97** [comment]
I added instructions to the text field now, I think is faster to use the keyboard to write a single character than to use the mouse to push a button.

![2020-08-25_14-55](https://user-images.githubusercontent.com/5056411/91221261-07243700-e6e3-11ea-9b04-64521ff853aa.png)
